name: Deploy to VPS

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      run: |
        sudo apt-get install -y sshpass
        mkdir -p ~/.ssh
        ssh-keyscan -H 143.198.50.21 >> ~/.ssh/known_hosts

        cd kindlecast
        sshpass -p "22222WaminZ" rsync -avz --delete --exclude='node_modules' --exclude='.next' --exclude='.git' ./ root@143.198.50.21:/var/www/kindlecast/

        sshpass -p "22222WaminZ" ssh root@143.198.50.21 "cd /var/www/kindlecast && npm install && pm2 delete kindlecast || true && pm2 start 'npm run dev' --name kindlecast && pm2 save"
